[2024-03-24T16:30:26.736+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-19T00:00:00+00:00 [queued]>
[2024-03-24T16:30:26.781+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-19T00:00:00+00:00 [queued]>
[2024-03-24T16:30:26.784+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-24T16:30:26.853+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-19 00:00:00+00:00
[2024-03-24T16:30:26.866+0000] {standard_task_runner.py:60} INFO - Started process 402 to run task
[2024-03-24T16:30:26.900+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-19T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpb_z5jzwn']
[2024-03-24T16:30:26.913+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask export_data_to_db
[2024-03-24T16:30:27.003+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-24T16:30:27.384+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-19T00:00:00+00:00 [running]> on host cc0f04bb20f0
[2024-03-24T16:30:27.981+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-19T00:00:00+00:00'
[2024-03-24T16:30:27.987+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-24T16:30:27.990+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-19 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-24T16:30:28.032+0000] {subprocess.py:86} INFO - Output:
[2024-03-24T16:30:30.473+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-24T16:30:30.674+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240319T000000, start_date=20240324T163026, end_date=20240324T163030
[2024-03-24T16:30:30.806+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-24T16:30:30.918+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-24T16:50:41.476+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-19T00:00:00+00:00 [queued]>
[2024-03-24T16:50:41.558+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-19T00:00:00+00:00 [queued]>
[2024-03-24T16:50:41.562+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-24T16:50:41.651+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-19 00:00:00+00:00
[2024-03-24T16:50:41.676+0000] {standard_task_runner.py:60} INFO - Started process 315 to run task
[2024-03-24T16:50:41.708+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-19T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpd5b78wyt']
[2024-03-24T16:50:41.728+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask export_data_to_db
[2024-03-24T16:50:41.857+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-24T16:50:42.098+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-19T00:00:00+00:00 [running]> on host 1ef4dfe662c6
[2024-03-24T16:50:42.751+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-19T00:00:00+00:00'
[2024-03-24T16:50:42.780+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-24T16:50:42.792+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-19 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-24T16:50:42.899+0000] {subprocess.py:86} INFO - Output:
[2024-03-24T16:50:45.168+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-24T16:50:45.329+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240319T000000, start_date=20240324T165041, end_date=20240324T165045
[2024-03-24T16:50:45.492+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-24T16:50:45.730+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-24T17:29:09.031+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-19T00:00:00+00:00 [queued]>
[2024-03-24T17:29:09.303+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-19T00:00:00+00:00 [queued]>
[2024-03-24T17:29:09.306+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-24T17:29:09.435+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-19 00:00:00+00:00
[2024-03-24T17:29:09.474+0000] {standard_task_runner.py:60} INFO - Started process 347 to run task
[2024-03-24T17:29:09.518+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-19T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpdy79joxv']
[2024-03-24T17:29:09.535+0000] {standard_task_runner.py:88} INFO - Job 14: Subtask export_data_to_db
[2024-03-24T17:29:09.656+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-24T17:29:09.939+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-19T00:00:00+00:00 [running]> on host 77fbfb9df273
[2024-03-24T17:29:10.552+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-19T00:00:00+00:00'
[2024-03-24T17:29:10.568+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-24T17:29:10.576+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-19 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-24T17:29:10.644+0000] {subprocess.py:86} INFO - Output:
[2024-03-24T17:29:12.726+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-24T17:29:12.981+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240319T000000, start_date=20240324T172909, end_date=20240324T172912
[2024-03-24T17:29:13.202+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-24T17:29:13.294+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
